apiVersion: v1
kind: Service
metadata:
  name: urlshrink-service
  labels:
    app: urlshrink
spec:
  type: LoadBalancer
  selector:
    app: urlshrink
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  sessionAffinity: None
